<?php

/**
 * Actions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    const
 * @subpackage model
 * @author     dimonze
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Actions extends BaseActions
{

  public function addGenerallParams()
  {
    $result = 0;
    if (!$this->getAdditionalParams() && $this->getWithoutGeneralParams()) {
      return 2;
    } else {
      return $this->getAdditionalParams() + $this->getWithoutGeneralParams();
    }
  }

}
