<?php

/**
 * Cron_taskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Cron_taskTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Cron_taskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cron_task');
    }
}