<?php

/**
 * Current_stateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Current_stateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Current_stateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Current_state');
    }
}