<?php

/**
 * EnvsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EnvsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EnvsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Envs');
    }
}