<?php

/**
 * EnvTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EnvTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EnvTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Env');
    }
}