<?php

/**
 * Parameters
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    const
 * @subpackage model
 * @author     dimonze
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Parameters extends BaseParameters
{

  public function getParamsValueArray()
  {
    $string = preg_split("/,/", $this->getParamsValue());
    foreach ($string as &$value)
    {
      $value = trim($value);
    }
    return $string;
  }

  public function getOsRelatedParams($ostype)
  {
    $result = preg_split("/,/", $this->getParamsValue());

    foreach ($result as $value)
    {
      if (preg_match("/" . $ostype . "/", $value)) {
        return preg_split("/::/", $value)[1];
      }
    }
    return $this->getParamsValue();
  }

}
