<?php

/**
 * TemlatesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TemlatesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TemlatesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Temlates');
    }
}