<?php

/**
 * TemplatesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TemplatesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TemplatesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Templates');
    }
}