<?php

/**
 * VmsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VmsTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object VmsTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Vms');
  }

  public function getDynamicVms($user)
  {
    return $this->createQuery('v')
                    ->where(('v.owner LIKE ?'), $user)
                    ->andWhere('v.static LIKE 0')
                    ->execute();
  }
  
  public function getEnvList($user)
  {
    return $this->createQuery('v')
                    ->select('v.access_vm_short_name, v.access_vm_ip')
                    ->where(('v.owner LIKE ?'), $user)
                    ->andWhere('v.static LIKE 0')
                    ->groupBy('v.access_vm_ip')
                    ->execute();
  }

}
