<?php

/**
 * VmsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VmsTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object VmsTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Vms');
  }

  public function findSpecificVms($user, $accessvm)
  {
    return $this->createQuery('us')
                    ->where(('us.owner LIKE ?'), $user)
                    ->andWhere(('us.access_vm_id LIKE ?'), $accessvm)
                    ->execute();
  }

}
