generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Vms
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          vms
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display:            [id, =access_vm_short_name, vm_name, static, owner]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
