<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('users', 'full_name', 'string', '64', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('users', 'full_name');
    }
}