<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('users', 'hp_password');
    }

    public function down()
    {
        $this->addColumn('users', 'hp_password', 'string', '64', array(
             'notnull' => '1',
             ));
    }
}