<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('actions', 'additional_params', 'boolean', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('actions', 'action_type', 'string', '', array(
             'notnull' => '',
             ));
        $this->changeColumn('parameters', 'params_value', 'string', '1000', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('actions', 'additional_params');
        $this->removeColumn('actions', 'action_type');
    }
}