<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('parameters', 'optional', 'int', '2', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('parameters', 'optional');
    }
}