<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('parameters', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'params_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'params_value' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'params_type' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'description' => 
             array(
              'type' => 'text',
              'length' => '500',
             ),
             'owner' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('parameters');
    }
}