<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('current_state', 'clenup_comand');
        $this->addColumn('current_state', 'cleanup_command', 'string', '100', array(
             ));
    }

    public function down()
    {
        $this->addColumn('current_state', 'clenup_comand', 'string', '100', array(
             ));
        $this->removeColumn('current_state', 'cleanup_command');
    }
}