<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version11 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('env');
    }

    public function down()
    {
        $this->createTable('env', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'access_vm' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'env_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'hosted_on' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'descr' => 
             array(
              'type' => 'text',
              'length' => '',
             ),
             'owner' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }
}