<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('actions', 'public', 'boolean', '25', array(
             'notnull' => '1',
             ));
        $this->addColumn('users', 'show_public_actions', 'boolean', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('actions', 'public');
        $this->removeColumn('users', 'show_public_actions');
    }
}