<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('vms', 'ssh_user', 'string', '100', array(
             'notnull' => '1',
             ));
        $this->addColumn('vms', 'ssh_pass', 'string', '100', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('vms', 'ssh_user');
        $this->removeColumn('vms', 'ssh_pass');
    }
}