<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('vms', 'access_vm_full_name', 'string', '100', array(
             ));
        $this->changeColumn('vms', 'vm_host', 'string', '100', array(
             ));
        $this->changeColumn('vms', 'vm_ip', 'string', '100', array(
             ));
        $this->changeColumn('vms', 'vm_os', 'string', '15', array(
             ));
    }

    public function down()
    {

    }
}