<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {        
        $this->dropTable('vms');
    }

    public function down()
    {       
        $this->createTable('vms', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'access_vm_id' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'access_vm_alias' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'vm_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'vm_ip' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'vm_os' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '15',
             ),
             'description' => 
             array(
              'type' => 'text',
              'length' => '',
             ),
             'owner' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             ), array(
             'type' => 'InnoDB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }
}