<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version22 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('current_state', 'outputpath', 'string', '500', array(
             ));
        $this->changeColumn('current_state', 'cleanup_command', 'string', '500', array(
             ));
    }

    public function down()
    {

    }
}