<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('vms', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'access_vm_full_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'access_vm_short_name' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             'access_vm_ip' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'access_vm_hosted_on' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             'access_vm_descr' => 
             array(
              'type' => 'text',
              'length' => '500',
             ),
             'vm_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'vm_ip' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'vm_port' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'vm_os' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '15',
             ),
             'vm_resources' => 
             array(
              'type' => 'text',
              'length' => '500',
             ),
             'vm_description' => 
             array(
              'type' => 'text',
              'length' => '500',
             ),
             'vm_state' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'vm_snapshots' => 
             array(
              'type' => 'text',
              'length' => '500',
             ),
             'owner' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('vms');
    }
}