<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version23 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('current_state', 'post_action', 'text', '5000', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('current_state', 'post_action');
    }
}