detect_relations: false
options:
  type: InnoDB
  collate: utf8_general_ci
  charset: utf8

Users:
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    user:
      type: string(100)
      notnull: true
    password:
      type: string(64)
      notnull: true  
    role:
      type: string(100)
      notnull: true
    hp_user:
      type: string(100)
      notnull: true
    full_name:
      type: string(64)
      notnull: true  
    description: text    
  
Env:
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    access_vm:
      type: string(100)
      notnull: true
    env_name:
      type: string(100)
      notnull: true
    hosted_on:
      type: string(100)
      notnull: true
    descr: text
    owner:
      type: string(100)
      notnull: true
  relations:
    Vms:
      class: Vms
      local: id
      foreign: access_vm_id
      foreignAlias: Envs
      type: one
      foreignType: many
      onDelete: cascade
      
Vms:
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    access_vm_id:
      type: string(100)
      notnull: true
    access_vm_alias:
      type: string(100)
      notnull: true
    vm_name:
      type: string(100)
      notnull: true
    vm_ip:
      type: string(100)
      notnull: true  
    vm_os:
      type: string(15)
      notnull: false  
    description: text
    owner:
      type: string(100)
      notnull: true    
#  relations:
#    Env:
#      class: Env
#      local: access_vm_id
#      foreign: id
#      foreignAlias: Vms
#      type: many
#      foreignType: one
#      onDelete: cascade
      
Actions:
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    action_name:
      type: string(100)
      notnull: true      
    description: text
    sample_act: text
    additional_params:
      type: boolean
      notnull: true
    without_general_params:
      type: boolean
      notnull: true
    action_type:
      type: string(100)
      notnull: false
    owner:
      type: string(100)
      notnull: true
      
Parameters:
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    params_name:
      type: string(100)
      notnull: true
    params_value:
      type: string(1000)
    params_type: 
      type: string(100)
      notnull: true
    optional:
      type: int(2)
      notnull: true
    description: text
    owner:
      type: string(100)
      notnull: true

Templates:
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    temlate_name:
      type: string(100)
      notnull: true      
    description: text
    owner:
      type: string(100)
      notnull: true

Cron_task:
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    task_name:
      type: string(100)
      notnull: true      
    description: text
    owner:
      type: string(100)
      notnull: true

Current_state:
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    session_name:
      type: string(100)
      notnull: true      
    description: text
    owner:
      type: string(100)
      notnull: true      