detect_relations: false
options:
  type: InnoDB
  collate: utf8_general_ci
  charset: utf8

Users:
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    user:
      type: string(100)
      notnull: true
    password:
      type: string(64)
      notnull: true  
    role:
      type: string(100)
      notnull: true
    hp_user:
      type: string(100)
      notnull: true
    full_name:
      type: string(64)
      notnull: true  
    show_public_actions:
      type: boolean
      notnull: true
    description: text    
      
Vms:
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    access_vm_full_name:
      type: string(100)
    access_vm_short_name:
      type: string(100)
    access_vm_ip:
      type: string(100)
      notnull: true
    access_vm_hosted_on:
      type: string(100)
    access_vm_descr: text
    vm_name:
      type: string(100)
      notnull: true
    vm_host:
      type: string(100)
    vm_ip:
      type: string(100) 
    vm_port:
      type: integer(4)
    vm_os:
      type: string(15)  
    vm_resources: text
    vm_description: text
    vm_state: integer(4)
    vm_snapshots: text
    static: 
      type: boolean
      notnull: true
    owner:
      type: string(100)
      notnull: true   
      
Actions:
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    action_name:
      type: string(100)
      notnull: true      
    description: text
    sample_act: text
    additional_params:
      type: boolean
      notnull: true
    without_general_params:
      type: boolean
      notnull: true
    public:
      type: boolean
      notnull: true
    action_type:
      type: string(100)
      notnull: false
    owner:
      type: string(100)
      notnull: true
      
Parameters:
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    params_name:
      type: string(100)
      notnull: true
    params_value:
      type: string(1000)
    params_type: 
      type: string(100)
      notnull: true
    optional:
      type: int(2)
      notnull: true
    description: text
    owner:
      type: string(100)
      notnull: true

Templates:
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    temlate_name:
      type: string(100)
      notnull: true      
    description: text
    owner:
      type: string(100)
      notnull: true

Cron_task:
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    task_name:
      type: string(100)
      notnull: true      
    description: text
    owner:
      type: string(100)
      notnull: true

Current_state:
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    session_name:
      type: string(100)
      notnull: true      
    description: text
    owner:
      type: string(100)
      notnull: true      