generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Current_state
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          current_state
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display:            [id, =vm_name, action_name, state, owner]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
